# reference
# https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
name: Run Docker Image
on: [push]
jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Free Disk Space (Ubuntu)
          uses: jlumbroso/free-disk-space@main
          with:
            # this might remove tools that are actually needed,
            # when set to "true" but frees about 6 GB
            tool-cache: true
        container:
          image: carlasim/carla:0.9.15