# reference
# https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
name: Run Docker Image
on: [push]
jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        container:
            image: aschmelyun/cleaver:latest